// This file is generated by scripts/generate-voice-data.mjs.
// Do not edit it by hand.

export type OperatorVoiceRecord = {
  fileCode: string
  label: string
  category: 'Talk' | 'Battle' | 'Greeting'
  english: string
  japanese: string
  audioPath: string | null
}

export const operatorVoiceRecords: Record<string, OperatorVoiceRecord[]> = {
  "amiya": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "You work so hard, Doctor.",
      "japanese": "ドクター、お仕事お疲れ様です。",
      "audioPath": "char_002_amiya/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Dr. Kal'tsit told me you have to be 100% focused on your work to maximize efficiency. So... yes, that's what I'm gonna do!",
      "japanese": "ケルシー先生が言ってました、仕事をする時は集中しなければいけない、と……。うん、集中しなきゃ。",
      "audioPath": "char_002_amiya/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "Rhodes Island has achieved cruising speed, Doctor. Would you mind sorting out the navigation log for me?",
      "japanese": "ロドスは全艦通常航行モードです。ドクター、航行スケジュールをチェックしませんか？",
      "audioPath": "char_002_amiya/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "I still have a lot to learn as leader of Rhodes Island. I hope you'll be there to guide me on our path to the future.",
      "japanese": "ロドスのリーダーとして私はまだまだ未熟で……ですから、これからの進むべき道を、もっと教えてくださいね。",
      "audioPath": "char_002_amiya/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "Maybe it's just wishful thinking, but I hope Rhodes Island can be like a second home to everyone.",
      "japanese": "これは私の身勝手な考えかもしれません。でも、ロドスのみなさんにとって、ここが第二の故郷になってくれたら嬉しいな……。",
      "audioPath": "char_002_amiya/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "Making it this far has cost us so much. Sometimes, I can't help but ask myself... is it really worth it?",
      "japanese": "たくさんのものを失いながら、ようやくここまでたどり着きました。でも…時々不安になってしまいます。本当にこれでよかったのかなと……。",
      "audioPath": "char_002_amiya/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "Sometimes I remember where I came from... It was cold, and the air smelled of rusted copper. Rhodes Island is a cozy place in comparison. I'll do everything I can to protect our home.",
      "japanese": "時々、故郷のことを思い出します。とても寒くて、街の空気からも錆臭い匂いが漂うようなところでした。それに比べて、ロドスはこんなにも暖かい……。だから、私はもっともっと頑張って、しっかりこの場所を守っていかなければならないと思っています……。",
      "audioPath": "char_002_amiya/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "Hehe… Dr. {@nickname}, let me tell you something: I picked up the violin again.",
      "japanese": "ふふ…実は私、またヴァイオリンの練習をし始めたんです。今度のパーティーでみなさんにサプライズを……だからドクター、みなさんには内緒ですよ……？",
      "audioPath": "char_002_amiya/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "We've still got a long, long way to go, Doctor. This might be a journey without an end, but as long as you're with me, we'll be okay.",
      "japanese": "ドクター、私たちの歩む道は、終わりなき旅路なのかもしれません……でも、それをドクターと共に歩むことができて、私はとても幸せです。",
      "audioPath": "char_002_amiya/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "There's still lots of work that needs to be done, Doctor. We can't afford to have you resting.",
      "japanese": "ドクター、終わってない仕事がたくさんありますから、まだ休んじゃだめですよ。",
      "audioPath": "char_002_amiya/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "I'm so glad you're back, Doctor. Now we can walk this path together, me with you, and you with me.",
      "japanese": "ドクター、また会えて……嬉しいです。私たちのゆく道は、まだ長く険しいものですが……とにかくこれからもよろしくお願いします。",
      "audioPath": "char_002_amiya/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "I see... thank you, Doctor! I've learned so much from you.",
      "japanese": "なるほど……本当に役に立つ知識ばかりです。ドクター、ご指導いただきありがとうございます！",
      "audioPath": "char_002_amiya/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "I'm so excited to fight by your side again, Doctor!",
      "japanese": "ドクター、またあなたと一緒に戦えて、本当に嬉しいです！",
      "audioPath": "char_002_amiya/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "What I saw that day... the despair stuck in my throat, hopelessly trying to scream... I want to bury it all deep inside my mind and never let it out…",
      "japanese": "あの日の目に焼き付いた光景、叫びたくても声を出せないほどの絶望感……全部記憶の奥底に閉じ込められたらいいのに……。",
      "audioPath": "char_002_amiya/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "Got it.",
      "japanese": "はい、わかりました。",
      "audioPath": "char_002_amiya/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "I won't let you down.",
      "japanese": "みなさんの期待に応えてみせます！",
      "audioPath": "char_002_amiya/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Operation commencing!",
      "japanese": "行動開始します！",
      "audioPath": "char_002_amiya/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Incoming! Get ready, everyone!\n",
      "japanese": "敵が来ます！みなさん、戦闘の準備をしてください！",
      "audioPath": "char_002_amiya/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "Here.",
      "japanese": "はい。",
      "audioPath": "char_002_amiya/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "I'm right here, Doctor.",
      "japanese": "ドクター、私はここに。",
      "audioPath": "char_002_amiya/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Got it!",
      "japanese": "わかりました！",
      "audioPath": "char_002_amiya/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Roger.",
      "japanese": "了解しました。",
      "audioPath": "char_002_amiya/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "I know what you're thinking.",
      "japanese": "あなたの考えは、お見通しですよ。",
      "audioPath": "char_002_amiya/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "Everyone believes in me...",
      "japanese": "みなさんが私のことを信じてくれてますから！",
      "audioPath": "char_002_amiya/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "Are you afraid of me?\n",
      "japanese": "私が、怖いですか？",
      "audioPath": "char_002_amiya/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "I hear... someone crying?",
      "japanese": "この声は……泣いている？",
      "audioPath": "char_002_amiya/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "No matter how difficult the mission, we can handle it as long as you're here, Doctor. I've never doubted you.",
      "japanese": "どんなに困難な任務でも、ドクターさえいれば、きっと大丈夫だと信じてます！",
      "audioPath": "char_002_amiya/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "We may have achieved a perfect victory, but we still can't let our guard down.",
      "japanese": "みなさん、完璧な勝利でも、警戒態勢が完全に解かれるまでは、気を抜かないでくださいね！",
      "audioPath": "char_002_amiya/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "Well done, Doctor! You must be exhausted. Be sure to rest when you need it.",
      "japanese": "ドクター、お疲れ様でした！無理をせず少し休んでくださいね。",
      "audioPath": "char_002_amiya/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "I'm fine... Get it together, everyone!",
      "japanese": "私は大丈夫です……みなさん、しっかりしてください！",
      "audioPath": "char_002_amiya/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "You want something to drink, Doctor?",
      "japanese": "何か飲みませんか、ドクター？",
      "audioPath": "char_002_amiya/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Huh? Doctor?",
      "japanese": "きゃっ？ドクター？",
      "audioPath": "char_002_amiya/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "Ehehe...",
      "japanese": "えへへ……。",
      "audioPath": "char_002_amiya/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_002_amiya/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Happy New Year, Doctor! Please make sure you get lots of rest today... Y-You've already worked for the better part of the day? Did I get here too late? Sorry...Blaze just asked me to get my height measured... Oh, you're just joking? Thank goodness.",
      "japanese": "明けましておめでとうございます、ドクター！今日くらいはどうぞ休んでくださいね……もう大分働いたんですか？ご、ごめんなさい、来るのが遅すぎたみたいですね。さっきブレイズさんに呼ばれて身長を測りに行っていて……冗談だったんですか？良かった……",
      "audioPath": "char_002_amiya/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Welcome home, Doctor!",
      "japanese": "おかえり、ドクター！",
      "audioPath": "char_002_amiya/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "I remember the names of those who've left us, and I can still feel the lingering fear, rage, and pain of battle. But if I'm to give a speech in front of everyone, I want to tell a story of hope instead. Doctor, I'm a little nervous... Could you hold my hand, please?",
      "japanese": "消えてしまった人たちの名前は、みんな覚えています。戦場の恐怖や怒り、そして苦しみの残響も、まだ感じ取れます。でも、みなさんの前でスピーチをするのなら、もっと希望に満ちたお話がしたいんです。ドクター、私なんだか緊張していて……手を握ってもらってもいいですか？",
      "audioPath": "char_002_amiya/CN_044.mp3"
    }
  ],
  "texas": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "My next mission is to protect you, Doctor.",
      "japanese": "次の任務はドクターの身辺警護か。",
      "audioPath": "char_102_texas/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "I don't say much? That's because I'd rather avoid thinking about most things.",
      "japanese": "無口だと？それは私が大抵のことに感慨を抱かないからだ……。",
      "audioPath": "char_102_texas/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "Our job is to deliver life and death.",
      "japanese": "我々の仕事は、生と死を運ぶことだ。",
      "audioPath": "char_102_texas/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "I usually listen to Sora's songs when I'm driving.",
      "japanese": "運転中は大抵、ソラが録った曲を聴いている。",
      "audioPath": "char_102_texas/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "Cigarette? Oh, no, this is chocolate. You've gotta replenish your energy regularly. Which reminds me... do you want some coffee?",
      "japanese": "タバコ？いや、これはチョコレートだ。エネルギーの定期摂取は必要だからな。そうだな……コーヒーでも飲むか？",
      "audioPath": "char_102_texas/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "How long have I worked for Penguin Logistics? When did I start...? I don't even know how long it's been.",
      "japanese": "いつからペンギン急便で働いているか？……いつから……そんなこと、とうに忘れた。",
      "audioPath": "char_102_texas/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "Watch out for the Red Wolf. She's not evil, but... she's not like us.",
      "japanese": "赤いオオカミには気をつけた方がいい。悪いやつではないが……私たちとは違う。",
      "audioPath": "char_102_texas/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "No matter how hard I run, my past will catch up to me one day.",
      "japanese": "いくら逃げたところで、いつかは過去に追いつかれる。",
      "audioPath": "char_102_texas/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "My independent lifestyle and rowdy friends have brought me a lot of trouble... but I kind of like it this way.",
      "japanese": "自由な生活、騒がしい仲間……いろいろ面倒だが……今はそれも悪くない気がする。",
      "audioPath": "char_102_texas/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "Is it time for a break?",
      "japanese": "今は休憩時間なのか？",
      "audioPath": "char_102_texas/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "Code name Texas. I'm responsible for driving, moving cargo, and keeping our people safe. Try to get the mission briefings as concise as possible, please.",
      "japanese": "名前はテキサス。仕事は車両の運転と物資の輸送、そして要人の警護だ。任務に関する指示は、できるだけシンプルに頼む。",
      "audioPath": "char_102_texas/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "Thanks.",
      "japanese": "どうも。",
      "audioPath": "char_102_texas/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "This will work as payment.",
      "japanese": "報酬なら、これで十分だ。",
      "audioPath": "char_102_texas/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "Thanks for trusting me, Doctor.",
      "japanese": "ドクターの信頼に感謝を。",
      "audioPath": "char_102_texas/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "What do you need?",
      "japanese": "何をすればいい？",
      "audioPath": "char_102_texas/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "I'm not good at barking orders.",
      "japanese": "誰かに指示を出すのは苦手だ。",
      "audioPath": "char_102_texas/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Let's go.",
      "japanese": "出発する。",
      "audioPath": "char_102_texas/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Exusiai, cover me.",
      "japanese": "エクシア、援護を。",
      "audioPath": "char_102_texas/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "Awaiting orders.",
      "japanese": "命令を。",
      "audioPath": "char_102_texas/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "Got it.",
      "japanese": "了解した。",
      "audioPath": "char_102_texas/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Draw swords!",
      "japanese": "抜刀。",
      "audioPath": "char_102_texas/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Let's begin.",
      "japanese": "始めよう。",
      "audioPath": "char_102_texas/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "Hah!",
      "japanese": "ふん。",
      "audioPath": "char_102_texas/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "You can't stop me.",
      "japanese": "誰にも縛られるつもりはない。",
      "audioPath": "char_102_texas/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "Cut them to pieces!",
      "japanese": "斬り尽くす。",
      "audioPath": "char_102_texas/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "Shut up.",
      "japanese": "黙っていろ。",
      "audioPath": "char_102_texas/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "Whew... No problem.",
      "japanese": "フッ…問題ない。",
      "audioPath": "char_102_texas/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "Weaklings.",
      "japanese": "脆い。",
      "audioPath": "char_102_texas/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "A few of them got through.",
      "japanese": "若干名の侵入を許した。",
      "audioPath": "char_102_texas/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "I may have underestimated this operation.",
      "japanese": "今回の任務を甘く見ていたようだ……。",
      "audioPath": "char_102_texas/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "Do you need any supplies? Just let me know.",
      "japanese": "必要な物資はあるか？助けになろう。",
      "audioPath": "char_102_texas/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Oh...!",
      "japanese": "ウッ……。",
      "audioPath": "char_102_texas/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "What is it, Doctor?",
      "japanese": "どうした、ドクター？",
      "audioPath": "char_102_texas/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_102_texas/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Happy New Year. I was just about to give these to Exusiai. She said she'd be hosting a big party tonight, to celebrate her results not being rock bottom. The other girls? Croissant was hauling a huge batch of goods she got in earlier, so I figure she's got a stall laid out now. As for Sora... have you heard her new single, Doctor? I'm pretty into it.",
      "japanese": "あけましておめでとう。ちょうどこれをエクシアに届けるところだ。営業成績が最下位にならなかったことを祝って、パーティーを開くらしい。クロワッサンはついさっき仕入れた商品の積み卸しをしていたから、今頃露店を開いているだろうな。そうだ、ソラの新曲は聴いたか？なかなか良い仕上がりだと思う。",
      "audioPath": "char_102_texas/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Morning.",
      "japanese": "おはよ。",
      "audioPath": "char_102_texas/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "I like how Rhodes Island does its anniversaries. Here's a couple wine truffles I just picked up, rum and bitter almond flavor. Tastes pretty good. Why don't you give them a try?",
      "japanese": "ロドスのこういう記念日も悪くないな。ほら、ボンボンショコラを取ってきた。中にラムとアマレットが入ってて、なかなかいけるから食べてみてくれ。",
      "audioPath": "char_102_texas/CN_044.mp3"
    }
  ],
  "exusiai": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "Hey, leader! Got some work for us?",
      "japanese": "リーダー、何か仕事をまわしてちょ。",
      "audioPath": "char_103_angel/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Leader, how about we throw a party? We can play some hip-hop and eat apple pie. The best life is the party life! No party, no life!",
      "japanese": "リーダー、パーティーでもしない？ヒップホップ流して、アップルパイなんかも焼いちゃってさぁ。完璧な人生にパーティはつきもの。ノーパーティ、ノーライフってね。",
      "audioPath": "char_103_angel/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "Locked and loaded, ready for action! What's the objective today, Leader?",
      "japanese": "弾薬装填、準備オーケー★ リーダー、今日の配達物はなんだい？",
      "audioPath": "char_103_angel/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "Some people believe money can buy anything. But, uh-uh, that saying doesn't really apply to me. Wealth won't make a lick of difference to where my targets end up.",
      "japanese": "金さえあれば何でも手に入るなんて言う奴もいるけど、あたしにゃ通用しないよ。たとえどんな大金持ちでも、あの世に送ってやればそれっきり～。",
      "audioPath": "char_103_angel/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "My first wish: more guns! We angels all have a patron firearm, a special gun we grow up with, but owning just one gun is kinda lame. I want eight more!",
      "japanese": "お願いその一！銃を八丁ほどプレゼントよろしく！あたしたち天使はみんな自分の守護銃を持ってるけど、一丁だけじゃしょぼいんだよね！",
      "audioPath": "char_103_angel/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "My second wish: get someone to turn off this light over my head!",
      "japanese": "お願いその二……誰かこの頭の上の蛍光灯を消して！",
      "audioPath": "char_103_angel/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "I've always got Texas covered, that's why she lives so carefree. So obvious it goes without saying, right?",
      "japanese": "テキサスのやつが、あーんなに生き生きとしているのは、あたしのおかげだよ。こんなこと、言うまでもないでしょ？",
      "audioPath": "char_103_angel/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "If you ever run into an angel with black horns oozing ominous vibes, please tell her for me: I've never forgotten her.",
      "japanese": "もし、黒い角が生えてて、全身からヤバそうなオーラが出てる天使に会ったら、エクシアはキミのことを忘れてないよって伝えといてほしいな。",
      "audioPath": "char_103_angel/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "Us Penguin Logistics girls ain't so bad, right? What do you say, leader? Wanna come be our boss? Hehe, just kidding.",
      "japanese": "リーダー、ペンギン急便も悪くないでしょ？うちのボスとかやってみちゃう？ふふ～冗談だよ～。",
      "audioPath": "char_103_angel/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "Oh Lord… is this another soul for us to save?",
      "japanese": "……主よ、この人にも救済が必要なのでしょうか？",
      "audioPath": "char_103_angel/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "Password: 'Long live the Penguin Empire.' So you're the client? Call me Exusiai. I'm nothing like that Lupo ice queen. I'm always down for some fun!",
      "japanese": "合言葉は「ペンギン帝国万歳」、アンタが今回の雇い主？あたしのことはエクシアって呼んでね。あの無愛想なオオカミとは違って、声をかけてくれればいつでも遊んであげるよ！",
      "audioPath": "char_103_angel/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "I'm lovin' this feeling!",
      "japanese": "こーいう感じ好きかも！",
      "audioPath": "char_103_angel/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "Thanks for the promotion, leader.",
      "japanese": "ごひいきにしてくれて、ありがと～！",
      "audioPath": "char_103_angel/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "Leader... No, savior, I swear on this gun in my hand, I will protect you until the day of reckoning.",
      "japanese": "リーダー……いや、義人よ、この銃に誓って、あなたを最後の審判までお守りします。",
      "audioPath": "char_103_angel/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "Squad combat? I'm very familiar with that.",
      "japanese": "チームでの戦い、慣れてるからまっかせて～！",
      "audioPath": "char_103_angel/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "You've got a good eye. No one makes a better leader than me.",
      "japanese": "キミ、人を見る目あるね！あたしより隊長にふさわしいやつはいないって！",
      "audioPath": "char_103_angel/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Let's go! Take them all by storm!",
      "japanese": "行くよ！嵐のように蹂躙してやる！",
      "audioPath": "char_103_angel/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Relax, I already called dibs on the most lucrative real estate in Hell, to share with all of you.",
      "japanese": "キミたちのために地獄の一等地に部屋を用意しておいたから！安心していってらっしゃい！",
      "audioPath": "char_103_angel/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "All right!",
      "japanese": "よーし！",
      "audioPath": "char_103_angel/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "Is it my turn?",
      "japanese": "あたしの出番？",
      "audioPath": "char_103_angel/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Follow me!",
      "japanese": "ついてきて！",
      "audioPath": "char_103_angel/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Let me double their trouble.",
      "japanese": "ちょっとからかってあげよーっと。",
      "audioPath": "char_103_angel/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "Divine judgment!",
      "japanese": "ディオ・ヴォーレント！",
      "audioPath": "char_103_angel/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "Rock n' roll!",
      "japanese": "ロックン・ロール！",
      "audioPath": "char_103_angel/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "Barrage!",
      "japanese": "バラージュ！",
      "audioPath": "char_103_angel/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "Apple pie!",
      "japanese": "アップルパイ！",
      "audioPath": "char_103_angel/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "Perfect! Let's keep up the momentum and charge on!",
      "japanese": "よし！このまま突き進もう！",
      "audioPath": "char_103_angel/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "May my hail of bullets bring you eternal peace.",
      "japanese": "銃弾の雨で、あなたたちを苦痛から救済しよう。",
      "audioPath": "char_103_angel/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "Victory is a heavenly melody. Alright, let's go home and grab some beers!",
      "japanese": "勝利の知らせは甘美なる福音。よーし、帰って飲もう！",
      "audioPath": "char_103_angel/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "Life is like a gun, sometimes it just jams. Don't get discouraged, leader, we'll get'em next time.",
      "japanese": "ま、銃だって詰まるときはあるし、人生も同じだよ。気にしない気にしない。",
      "audioPath": "char_103_angel/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "Wowee! I love this place!",
      "japanese": "ここ、気に入った！",
      "audioPath": "char_103_angel/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Oh!",
      "japanese": "よっ！",
      "audioPath": "char_103_angel/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "Leader, wanna try out my weapon?",
      "japanese": "リーダー！あたしの武器、試してみる？",
      "audioPath": "char_103_angel/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_103_angel/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Happy New Year, Leader! The party's about to start, Employee Performance Competition Night's over, and I'm not dead last! Here's your booze and apple pie. Let's heat ourselves up to the hip-hop beat, and set this firework tower to the sky~ Here we go! Three, two—BANG!",
      "japanese": "リーダー、ハッピーニューイヤー！もうすぐパーティが始まるよ！こっちはやっと最終営業日が終わったとこだけど、成績ビリは回避したから心置きなく楽しもう！はい、リーダーの分のお酒とアップルパイ。さーて、ヒップホップのビートにノってあそこの花火タワーに点火しちゃいますか！いっくよー、三、二、一――ドッカーン！",
      "audioPath": "char_103_angel/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Sup, leader!",
      "japanese": "やっほー！リーダー！",
      "audioPath": "char_103_angel/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "We are led in differing directions. But by your power and wisdom, you may guide us on our journey together. Should the soul in you that protects us be a constant, we too will open a brand new path for you by our souls of honesty and ardor.",
      "japanese": "私たちは皆、異なる道を歩んできました。ですが、どうか今こそ、あなたの力と知恵を以て皆を一つの旅路へとお導きください。私たちを守るというあなたの想いが不変であれば、同じく不変なる誠意と熱意で応え、新たな道を切り拓いてみせましょう。",
      "audioPath": "char_103_angel/CN_044.mp3"
    }
  ],
  "silverash": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "There are better ways to kill time. Care to try one?",
      "japanese": "暇つぶしならいい方法があるが、試してみるか？",
      "audioPath": "char_172_svrash/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Why the constant sullen face? Can't you at least smile for me? Good. That's what I want to see... Yes, there's no one better suited to solve your problems than me... Isn't that right?",
      "japanese": "そんな浮かない顔はやめろ。私の前ではもっと楽しそうにしてくれ……よし、その調子だ。お前が抱えている問題を解決できるのは、この私のほかにはいないのだからな——そうだろう。",
      "audioPath": "char_172_svrash/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "That girl... Amiya, I believe her name was? She's no ordinary girl. If you don't put shackles on her wrists today, you will find yourself placing a crown upon her head tomorrow.",
      "japanese": "あの少女……名をアーミヤというのか……只者ではないな。今のうちに枷をかけておかないのであれば、近い未来、彼女を王とする覚悟が必要だな。",
      "audioPath": "char_172_svrash/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "The stability of the alliance between Karlan and Rhodes Island depends solely on your state of mind, and mine. As such, we should at least try to get along, my friend.",
      "japanese": "カランドとロドスが、どれだけ強固な信頼関係を築けるかは、我々の考え方次第なのだ。ならば、せいぜい仲良くやろうじゃないか。我が盟友よ。",
      "audioPath": "char_172_svrash/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "I suppose... it's high time I signed this contract. Of course, I do know that the terms are in yours, and Rhodes Island's favor.",
      "japanese": "この条約、締結してやろうではないか。もちろん気づいている、すべての条文はお前、そしてロドスに有利な内容になっていることをな。",
      "audioPath": "char_172_svrash/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "I'm well aware that this contract offers me nothing... But what does that matter? I shall nonetheless accept this unequal treaty. The reason being that I, SilverAsh, recognize that you warrant it.",
      "japanese": "ふざけた条約であるとは承知しているが、それが何だと言うのだ。私はこの不平等な条約を受け入れよう――お前にはそれだけの価値があると、このシルバーアッシュが認めているということだ。",
      "audioPath": "char_172_svrash/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "Is Ensia giving you trouble? My apologies. It was originally my own responsibility to foster and guide her, but it's unlikely I will be able to do so. So I must ask... could you do it in my stead, {@nickname}?",
      "japanese": "エンシアが迷惑をかけてはいないか？悪いな……あの子の世話と指導は本来であれば私の役目なのだが、これだけは力になれそうにない。だから{@nickname}、私の代わりを頼まれてくれないだろうか。",
      "audioPath": "char_172_svrash/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "Could you show me to Rhodes Island's deck? No, I'd just like to get a view of the area. Tenzin needs to spread his wings every once in a while as well. He must be longing to soar through the night sky.",
      "japanese": "甲板への案内を頼めるか？いや、外を眺めるだけだ。テンジンもしばらく羽を広げていないから、荒野の空気が恋しくなっただろうしな。",
      "audioPath": "char_172_svrash/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "If this continues, there will come a day when you and I confront one another... I seem delighted, you say? Hah, perhaps I am. You would be a worthy opponent, that's for certain. Let us make the most of our time before that day comes.",
      "japanese": "このままいけば、お前と対峙する日が——いずれは訪れるだろう。私が嬉しそうだと？フッ、そうかもしれんな。相手がお前なら、期待も膨らむというものだ。その日が来るまで、残された時間を有意義に過ごすとしよう。",
      "audioPath": "char_172_svrash/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "When the aether darkens, 'tis an omen that snowfall draws near...'",
      "japanese": "――空陰りなば、そは雪舞う兆しなり――。",
      "audioPath": "char_172_svrash/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "I, SilverAsh, have joined your cause as a sworn ally. Whatever your plans may be, do not disappoint me.",
      "japanese": "シルバーアッシュ。盟友として参戦する。この私を失望だけはさせてくれるなよ。",
      "audioPath": "char_172_svrash/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "For one to travel such an arduous path, one absolutely must have experience.",
      "japanese": "険しい道を踏破せんとするならば、経験が必要不可欠だ。",
      "audioPath": "char_172_svrash/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "Ostentatious titles are one thing, but the trust accompanying them is what concerns me. You surely know that.",
      "japanese": "煌びやかな肩書きそのものより、それに寄せられる信頼のほうにこそ価値がある。お前にもそれはわかるだろう。",
      "audioPath": "char_172_svrash/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "It takes a daring soul to drag me into their war. That being so, I, SilverAsh, will show my prowess for all of Rhodes Island to see.",
      "japanese": "この私を戦火に巻き込もうとはいい度胸だ――ならばこのシルバーアッシュの手並み、全てのロドス民に披露してやろう――！",
      "audioPath": "char_172_svrash/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "We all have our roles to play. Use my abilities as best you see fit.",
      "japanese": "郷に入っては郷に従え――お前は思うままに私を使えばいい。",
      "audioPath": "char_172_svrash/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "You wish me to act as your proxy? Very well. But you must pay me due tribute later.",
      "japanese": "お前の采配の助言をしろと？いいだろう。ただし対価は払ってもらうぞ。",
      "audioPath": "char_172_svrash/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Compassion saves no one on the battlefield.",
      "japanese": "仁愛では、戦場で誰も救えない。",
      "audioPath": "char_172_svrash/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Show me what you're made of. Amuse me, if you even can.",
      "japanese": "全力でかかってこい――私を楽しませてみろ。",
      "audioPath": "char_172_svrash/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "What are you planning?",
      "japanese": "何か考えがあるのか？",
      "audioPath": "char_172_svrash/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "Made up your mind?",
      "japanese": "決まったか？",
      "audioPath": "char_172_svrash/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Acknowledged.",
      "japanese": "承知した。",
      "audioPath": "char_172_svrash/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Very well.",
      "japanese": "いいだろう。",
      "audioPath": "char_172_svrash/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "'The fool flaunting his gallantry reaches none with his vanity...'",
      "japanese": "――汝らが誇示せし武勇、何人も語り継ぐこと叶わん――。",
      "audioPath": "char_172_svrash/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "'Fool, for what reason hast thou come?'",
      "japanese": "――汝、おのが存在を自らに問え――。",
      "audioPath": "char_172_svrash/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "'Art thou mine worthy enemy, or art thou naught but a jester?'",
      "japanese": "――汝は我が怨敵なるか、はたまた玩弄物に過ぎぬのか――。",
      "audioPath": "char_172_svrash/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "'Thy pleas falleth upon deaf ears.'",
      "japanese": "――汝らの哀鳴、我が威光に掻き消されたり――。",
      "audioPath": "char_172_svrash/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "The fiercer the battle, the more jubilant the victory.",
      "japanese": "厳しい戦いであればあるほど、勝利の喜悦がより甘美なものとなる。",
      "audioPath": "char_172_svrash/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "A satisfying battle. It brought palpitations even to my heart.",
      "japanese": "悪くない戦いだった。この私ですら、胸の高鳴りを感じたほどだ。",
      "audioPath": "char_172_svrash/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "We should strive for better.",
      "japanese": "さらなる高みを目指すべきだな。",
      "audioPath": "char_172_svrash/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "Retreat at once, while there is still time.",
      "japanese": "すぐ撤退しろ。まだ間に合う。",
      "audioPath": "char_172_svrash/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "For a place to rest my feet, it is acceptable.",
      "japanese": "足休めの拠点としては、まずまずだ。",
      "audioPath": "char_172_svrash/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Hmm?",
      "japanese": "ん？",
      "audioPath": "char_172_svrash/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "Let me rest for a brief while. I'm more tired than I thought. My apologies.",
      "japanese": "少しだけ……休ませてくれ。どうやら疲れているようだ、悪いな。",
      "audioPath": "char_172_svrash/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_172_svrash/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "The snow falls heavy... The blizzards of far-off Kjerag continue year after year, but the political landscape never stands still from one moment to the next. For those who fail to catch up with the changes, this age-old snowstorm will come to bury them beneath.",
      "japanese": "吹雪いてきたな……遙かイェラグの風雪は代わり映えしなくとも、政治の局面は刻一刻と変化し続けている。変化に取り残された者たちは皆、あの万年雪に埋もれていくのだろうな。",
      "audioPath": "char_172_svrash/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "You haven't changed one bit, my friend.",
      "japanese": "変わりはないか、我が盟友よ。",
      "audioPath": "char_172_svrash/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "Multiple times now, Rhodes Island has shown its ability and its responsibility as a medical firm. But I'm very curious. In your eyes, will this merely stop at Oripathy? What new ripples will you send across the lands in future? I have great expectations.",
      "japanese": "ロドスにはもう幾度となく医療機関たる資質と責任感を見せつけられた。しかし、お前の眼差しは果たして鉱石病だけに向けられているのか否か、興味深いところだ。これから先の未来、お前がこの大地にどんな波紋を呼ぶのか、楽しみにしているぞ。",
      "audioPath": "char_172_svrash/CN_044.mp3"
    }
  ],
  "nearl": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "Salutations, Doctor. May the light be with you.",
      "japanese": "ご機嫌麗しゅうドクター。あなたに光のご加護があらんことを。",
      "audioPath": "char_148_nearl/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Doctor, I ask that you give me the most dangerous assignment available, such that my shield and I can best protect those in need.",
      "japanese": "最も危険な場所への配属を志願する。この盾と私が、皆を守る。",
      "audioPath": "char_148_nearl/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "The title of 'Knight' should be a symbol of honor. And yet now, it's been reduced to a mere commodity...",
      "japanese": "「騎士」の称号とは誇りの象徴であろう。それがいつの間にか商売の道具に成り下がるとは……",
      "audioPath": "char_148_nearl/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "As long as the light continues to guide me, I will neither bow to cruelty nor kneel to violence.",
      "japanese": "どんな残虐非道にも決して屈しない。光の導きがある限り。",
      "audioPath": "char_148_nearl/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "I'm grateful as always for your service, Doctor.",
      "japanese": "ドクターにはいつも感謝している。",
      "audioPath": "char_148_nearl/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "The Kazimierz chivalric spirit should have been a force of salvation for all who suffer in this world. But now, it's nothing more than a rotten legacy, used to benefit the rich. Nothing is more shameful.",
      "japanese": "カジミエーシュの騎士道精神は、苦しむ者たちに救いの手を差し伸べるために生まれたものだ……しかし今となっては、上層部の資金繰りの道具へと成り下がってしまった。これ以上の屈辱はない。",
      "audioPath": "char_148_nearl/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "Shining, too, is a beam of light that guides me forward. She carries the hope I've long sought.",
      "japanese": "シャイニング……彼女は私を導く光……そして私が追い求める希望だ。",
      "audioPath": "char_148_nearl/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "Something flickered in Shining's eyes when she heard the name Rhodes Island. I had no idea what it meant...",
      "japanese": "ロドスという名を聞いたとき、何故かシャイニングは動揺していた……だがその理由はわからない。",
      "audioPath": "char_148_nearl/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "In this time and age of a world plagued by Oripathy, may the ray of hope from Rhodes Island light the way.",
      "japanese": "鉱石病に侵されたこの時代に、ロドスが希望の光とならんことを。",
      "audioPath": "char_148_nearl/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "Let us embrace this momentary respite.",
      "japanese": "束の間の安らぎを……。",
      "audioPath": "char_148_nearl/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "Margaret Nearl, the Radiant Knight of Kazimierz...and now a Rhodes Island Operator. I will defend your life and your honor with my shield.",
      "japanese": "マーガレット・ニアール。カジミエーシュの騎士……ではなく、ロドスのオペレーターとして、あなたの誇りと命を、この盾に誓って護ろう。",
      "audioPath": "char_148_nearl/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "Thank you for granting me power.",
      "japanese": "力を与えてくれたこと、感謝する。",
      "audioPath": "char_148_nearl/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "Thank you, Doctor. These new powers shall bring relief to those who suffer. This I shall engrave upon my heart.",
      "japanese": "感謝する、ドクター。いついかなる時も、この力は苦しむ者を救うためのものであると、肝に銘じよう。",
      "audioPath": "char_148_nearl/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "Shining once said that dawn remains distant. But I believe that, one day, we will revive the dying glory with our very own hands.",
      "japanese": "夜明けはまだ遠いとシャイニングは言うが、いつか必ず失われた栄光を取り戻せると、私は信じている。",
      "audioPath": "char_148_nearl/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "I shall protect them from all harm.",
      "japanese": "全ての害悪は私が振り払おう。",
      "audioPath": "char_148_nearl/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "I shall not blemish Rhodes Island's name.",
      "japanese": "ロドスの名に恥じぬ戦いを。",
      "audioPath": "char_148_nearl/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "I am ready. Set out!",
      "japanese": "準備完了。出立する。",
      "audioPath": "char_148_nearl/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Honor must be defended.",
      "japanese": "その誇り、守るために。",
      "audioPath": "char_148_nearl/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "In your name.",
      "japanese": "その名に誓って。",
      "audioPath": "char_148_nearl/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "I shall give my all to you.",
      "japanese": "この力、あなたのために尽くそう。",
      "audioPath": "char_148_nearl/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "I shall cover you!",
      "japanese": "援護する。",
      "audioPath": "char_148_nearl/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Get behind me!",
      "japanese": "私の後ろへ。",
      "audioPath": "char_148_nearl/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "Light, heed me!",
      "japanese": "光あれ。",
      "audioPath": "char_148_nearl/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "I'm with you!",
      "japanese": "私がついている。",
      "audioPath": "char_148_nearl/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "Don't be afraid.",
      "japanese": "心配無用だ。",
      "audioPath": "char_148_nearl/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "Revitalize!",
      "japanese": "目覚めよ。",
      "audioPath": "char_148_nearl/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "A true knight will not bend to the threat of violence. Now, repent for your sins, in front of my warhammer.",
      "japanese": "真の騎士は決して暴力に屈しない。この裁きの鉄槌の前に、おのが行いを悔いるがいい。",
      "audioPath": "char_148_nearl/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "Let us go forth. And there will be one day…",
      "japanese": "この歩み、進めてゆけば……いつか必ず……。",
      "audioPath": "char_148_nearl/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "A true knight will not chase one who's lost the will to fight. Everyone deserves a chance to choose a new path.",
      "japanese": "真の騎士は、敗者をどこまでも追い詰めたりはしない。どんな人間にも悔い改める機会は与えられるべきだ。",
      "audioPath": "char_148_nearl/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "We must not give up now.",
      "japanese": " ……ここで諦めてはいけない。",
      "audioPath": "char_148_nearl/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "I shall keep watch here.",
      "japanese": "ここでは見回り役を買って出よう。",
      "audioPath": "char_148_nearl/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "I sense an intru- Oh, Doctor?!",
      "japanese": "敵の様子がっ……ドクター？",
      "audioPath": "char_148_nearl/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "Doctor, umm... may I enter your office? I've heard you have a vast collection of literature.",
      "japanese": "ドクター、その……コホン、執務室に入らせてはもらえないだろうか？大量の蔵書があると聞いているので。",
      "audioPath": "char_148_nearl/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_148_nearl/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Tonight in the Grand Knight Territory, the corporations who've won the bidding war for firework permits will blanket the sky, and out in the barrens, destitute settlements will warm themselves on firewood as a rare luxury. While you can have your name written in those New Year's fireworks, I'm more than glad that I have brought those people firewood.",
      "japanese": "今晩、大騎士領のオークションで「花火権」を落札した企業は、花火で夜空を満遍なく飾り付けるだろう。一方、荒野の貧しい集落では珍しく贅沢に火をおこして暖を取る。新年の花火で自分の名前を見せるよりは、他人に薪を贈ったことを私は嬉しく思うのだ。",
      "audioPath": "char_148_nearl/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Good morning to you, Doctor.",
      "japanese": "いい朝だな、ドクター。",
      "audioPath": "char_148_nearl/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "When I was bestowed the title of Radiant Knight, the General Chamber of Commerce didn't much appreciate my shine. Fortunately, neither Shining nor Rhodes Island have since found me too bright to look at. As vast as the land is, I imagine the rays of the sun will only reach so far. In that respect, I will strive until I can strive no more.",
      "japanese": "私が耀騎士の称号を得た時、商業連合会は私の光をあまり評価していなかったが、幸運なことに、シャイニングとロドスは私を眩しすぎるとは感じなかった。そもそも、この大地の広さを鑑みれば、たとえ太陽の輝きであろうと眩しすぎるとは言えないだろう。だから私は、全力を尽くす所存だ。",
      "audioPath": "char_148_nearl/CN_044.mp3"
    }
  ],
  "ptilopsis": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "Greetings Doctor. How may I assist you?",
      "japanese": "こんにちは、ドクター。ご用件は何でしょう？",
      "audioPath": "char_128_plosis/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Deep Sleep Mode enabled... Zzzzz... Setting advanced config and power interface... Zzzzz…",
      "japanese": "……ディープスリープモード継続中……Zzzz……電源管理の設定を更新しています……Zzz……。",
      "audioPath": "char_128_plosis/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "My racial traits, in conjunction with my infection, may cause me to fall asleep in mid-conversation. Do not be alarmed.",
      "japanese": "種族の特性とウイルス感染の影響により、会話の途中で寝てしまうことがあります。どうかお気になさらないでください。",
      "audioPath": "char_128_plosis/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "I met Dr. Silence at Rhine Lab. I assisted her with data and risk analysis on a secret project.",
      "japanese": "サイレンスさんはライン生命にいた頃からの知り合いです。とあるプロジェクトで、彼女のためにビッグデータの分析とリスクアセスメントを行ってました。",
      "audioPath": "char_128_plosis/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "Warning! Formatting Rhodes Island database... Don't worry. It's just a joke. Please don't panic.",
      "japanese": "警告、これより、ロドスのデータベースを初期化します。……冗談です、そんなに慌てないでください。",
      "audioPath": "char_128_plosis/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "I recommend you refactor my data if optimization fails to increase my performance. This will improve communication efficiency, and Ptilopsis will... Zzzz...",
      "japanese": "最適化でのパフォーマンス上昇が見込めない場合、リファクタリングをおすすめいたします。データ通信の効率が上昇し、フィリオプシスは……Zzz……。",
      "audioPath": "char_128_plosis/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "The way I speak? It is a side effect of Originium poisoning. By no means do I enjoy articulating my thoughts this way.",
      "japanese": "この喋り方ですか？これは源石の影響です。決して面白がっているということはございません。",
      "audioPath": "char_128_plosis/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "Warning, system has recovered from a fatal error. Reconfiguring to last normal system boot point. Do not be alarmed.",
      "japanese": "警告、システムは重篤なエラーから回復しました。前回正常起動時の構成を適用中。どうかお気になさらず。",
      "audioPath": "char_128_plosis/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "It is, in fact, quite burdensome to speak in this manner. But this is a necessary measure to prevent the system nexus from being devoured by that other voice. Doctor, if I lose control, please guide me back onto the right path.",
      "japanese": "実をいうと、この喋り方はかなり負担がかかります。ですが、システム中枢があの声に飲み込まれないようにするためのものなのです……。ドクター、フィリオプシスが暴走してしまっても、どうか正しい道に導いてくれることを、切に願います。",
      "audioPath": "char_128_plosis/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "System... is now in Sleep Mode...",
      "japanese": "……システム、スリープモードに入ります。",
      "audioPath": "char_128_plosis/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "I am Ptilopsis, former data analyst at Rhine Lab. Please submit your orders via the Command Line.",
      "japanese": "ライン生命医科学研究所の元データアナリスト、フィリオプシスです。ご迷惑でなければ、コマンドラインによる命令を希望します。",
      "audioPath": "char_128_plosis/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "Reading package data… Installation complete.",
      "japanese": "パッケージを読み込み中……適用完了しました。",
      "audioPath": "char_128_plosis/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "Update installation complete. Ptilopsis's system permissions have been revised.",
      "japanese": "アップデータのインストール完了。フィリオプシスのシステム権限が更新されました。",
      "audioPath": "char_128_plosis/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "Warning. Reverting Rhodes Island database to previous save state. Time since save state: two years… Just joking. Please calm down. System update complete.",
      "japanese": "警告、これよりロドスのデータベースを二年前のバックアップから復元します。……冗談です、ご安心ください。システムのアップデートが完了しました。",
      "audioPath": "char_128_plosis/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "New data used to assemble package build.",
      "japanese": "新たなデータを、パッケージにビルドしました。",
      "audioPath": "char_128_plosis/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "Squad leader permissions acquired.",
      "japanese": "部隊管理者のアクセス権限を入手しました。",
      "audioPath": "char_128_plosis/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Direct memory access for application map and enemy coordinates authorized. Please stand by.",
      "japanese": "マップと敵座標のDMA設定を適用しています。少々お待ちください。",
      "audioPath": "char_128_plosis/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Tactical support system online.",
      "japanese": "戦術支援システム、オンライン。",
      "audioPath": "char_128_plosis/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "Program initializing.",
      "japanese": "プログラム、起動します。",
      "audioPath": "char_128_plosis/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "Initiation complete.",
      "japanese": "初期化、完了しました。",
      "audioPath": "char_128_plosis/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Arts Unit charging.",
      "japanese": "アーツユニット、チャージ中。",
      "audioPath": "char_128_plosis/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Target marked.",
      "japanese": "ターゲット、ロックオン。",
      "audioPath": "char_128_plosis/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "Initiating healing process.",
      "japanese": "医療プロセス、開始します。",
      "audioPath": "char_128_plosis/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "Loading complete.",
      "japanese": "ロード、完了しました。",
      "audioPath": "char_128_plosis/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "Healing Mode enabled.",
      "japanese": "治療モード、適用します。",
      "audioPath": "char_128_plosis/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "Activating Arts Unit.",
      "japanese": "アーツユニット、起動します。",
      "audioPath": "char_128_plosis/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "Even such a challenging scenario couldn't stop you, Doctor. Perhaps one day you will find the solution to the non-deterministic polynomial time problem.",
      "japanese": "高難易度のマップも攻略できるドクターであれば、いつか非決定性多項式時間の問題も、解明できると予想されます。",
      "audioPath": "char_128_plosis/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "Your logical deduction was absolutely correct. What a perfect calculation.",
      "japanese": "予測通りの戦いでした。完璧です。",
      "audioPath": "char_128_plosis/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "A number of errors have been detected. Please confirm.",
      "japanese": "若干のエラーを確認しました。ご注意ください。",
      "audioPath": "char_128_plosis/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "A fatal error occurred during the operation. Reboot the system to proceed.",
      "japanese": "作戦行動中に問題が発生しました。システムを再起動してください。",
      "audioPath": "char_128_plosis/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "Is this place like a disk array?",
      "japanese": "この場所はディスクアレイのようなものですか？",
      "audioPath": "char_128_plosis/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Error occured.",
      "japanese": "エラー発生。",
      "audioPath": "char_128_plosis/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "Detecting affection increase for the Doctor within Ptilopsis. Would you like to skip to the next dialogue choice?",
      "japanese": "フィリオプシス、ドクターへの好感度の上昇を感知しました。次の選択肢までスキップしますか？",
      "audioPath": "char_128_plosis/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_128_plosis/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Loading… Loading complete. File name: New Year. Date modified: twelve hours ago. Updating entry contents: Doctor, Happy New Year! Your present has been placed on your desk. Open it and take a look!",
      "japanese": "システムキーワード「新年」を検出。内容の読み込み完了。キーワードの最終更新時間――十二時間前。更新内容を復唱します――ハッピーニューイヤー、ドクター。プレゼントは執務室の机に置いてあります。早く開けてみましょう。",
      "audioPath": "char_128_plosis/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Date rollover complete. The Doctor is now online. Detecting emotional surge within Ptilopsis.",
      "japanese": "新たな一日、ドクターがオンラインになりました。フィリオプシスの感情の高まりを検知。",
      "audioPath": "char_128_plosis/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "Zzzzz... Detected passage of the Doctor. What is the Doctor laughing at...? Scanning hairstyle condition of Ptilopsis... Detected three pigtails, five bows, five colored bands, two clips. Assumed to be practical joke by Ifrit... Final assessment: Adorable.",
      "japanese": "Zzzzz……ドクターの通過を感知しました。なぜ笑っているのでしょうか？……フィリオプシスの髪型の状態スキャンを実行し、三つ編み三本、リボン五つ、カラーゴム五つ、ヘアクリップ二つを検出しました。イフリータによるイタズラだと推定されます……可愛いですね。",
      "audioPath": "char_128_plosis/CN_044.mp3"
    }
  ],
  "myrtle": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "Hey, Doctor. I'm here to hang!",
      "japanese": "やっほードクター、遊びに来たよー。",
      "audioPath": "char_151_myrtle/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Doctor, don't look down on me just 'cause I'm little. Back where I'm from, all the kids looked up to me.",
      "japanese": "ドクター、小さいからって甘く見ないでね！里にいた頃は、街の子たちがみ～んな、あたしの子分だったんだよ。",
      "audioPath": "char_151_myrtle/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "Durin used the name of our race as her codename because she's so lazy, but isn't it kind of dumb how calling me 'Myrtle of Durin' made me sound like I belong to her or something?",
      "japanese": "ドゥリンはきっと考えるのが面倒だったから、種族の名前をそのままコードネームにしたんだよね。でもそうなると、あたしが「ドゥリンのテンニンカ」って自己紹介すると、まるであの子のものみたいに聞こえちゃうから…それってずるくない？",
      "audioPath": "char_151_myrtle/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "I understand how all the machines here work, but it still feels weird using them. Some have a lot of different parts, but some are surprisingly simple.",
      "japanese": "ここの機械って、仕組みはわかるけど、なんか変な使い心地だね。余計に複雑なものもあれば、意外と簡単なのもあったりしてさ。",
      "audioPath": "char_151_myrtle/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "My banner? Good eye, Doctor. It sure is a tablecloth from my house. I sneaked it out with me because it can't get dirty. My dad is probably pretty mad about it!",
      "japanese": "この旗？ふふ、さすがドクター、いい目してるね。これはうちのテーブルクロスだったんだけど、どうやっても汚れなくて面白かったから、こっそり家から持ち出しちゃったの。へっへー、今頃パパは絶対怒ってるだろうね。",
      "audioPath": "char_151_myrtle/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "Is my apple really that great? They're popular back home. You can study or play with it if you want, Doctor, just don't break it.",
      "japanese": "え、あたしのリンゴちゃんがすごいって？う～ん、里ではわりと普通かな。ドクターが遊びたいとか研究したいとか言うなら貸してあげてもいいけど、壊さないでね。",
      "audioPath": "char_151_myrtle/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "There are still many things I'm not used to on land, but I love the many delicious foods. The cafe on Rhodes Island is my favorite!",
      "japanese": "地上にはまだ慣れないことがたくさんあるけど、おいしいものがいっぱいあるから楽しい！特にロドスの食堂は最高だよ！",
      "audioPath": "char_151_myrtle/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "I do have to point out the fact, Doctor, that I am a full-grown adult! And I'm tall by Durin standards! Please tell everyone to stop patting me on the head and giving me candy!",
      "japanese": "ドクター、真面目な話、あたしはね、もう成人してるから！それにドゥリンの中でも結構身長が高い方なの！だから、あたしを見るなり頭撫でながらおやつ渡すのをやめてってみんなに言ってよ！",
      "audioPath": "char_151_myrtle/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "Say, Doctor, are you interested in my homeland? I can take you there! But it's pretty far, so wait till I'm in the mood.",
      "japanese": "ねぇドクター、あたしの故郷には興味ある？連れてったげよっか！でも、あそこに着くまで結構歩くから、あたしがその気になってからにしよう。",
      "audioPath": "char_151_myrtle/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "Are you taking a break? You can use my banner as a blanket.",
      "japanese": "ドクター、休むの？じゃー、あたしの旗を布団代わりに貸してあげるね。",
      "audioPath": "char_151_myrtle/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "Reporting in! You must be the Doctor? Call me Myrtle, Myrtle of Durin. Durin said I could get a job here, so what have you got for me? I may be small, but I'm tough!",
      "japanese": "初めまして！あなたがドクター？あたしはテンニンカ、ドゥリン族のテンニンカだよ。ここなら仕事も見つかるってドゥリンが言ってたけど、何かあたしにできることない？背は小さいけど、あたしってすごいからね。",
      "audioPath": "char_151_myrtle/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "Cool fight... Got some more, Doctor?",
      "japanese": "ふむふむ……今の面白かったね。これってまだある？ドクター。",
      "audioPath": "char_151_myrtle/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "Oh, did I get promoted? Does that mean I can go somewhere I couldn't before?",
      "japanese": "え？昇進？あたしが？じゃあ、今まで行けなかったところに行ってもいい？",
      "audioPath": "char_151_myrtle/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "I told you I'm tough! Told you!",
      "japanese": "最初に言ったでしょ、あたしはすごいよって！えっへん！",
      "audioPath": "char_151_myrtle/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "There's a mission? I wanna go!",
      "japanese": "任務？行く行く！",
      "audioPath": "char_151_myrtle/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "Don't anyone wander away.",
      "japanese": "みんな、あまりあたしから離れないでね。",
      "audioPath": "char_151_myrtle/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Let's go!",
      "japanese": "しゅっぱーつ！",
      "audioPath": "char_151_myrtle/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "Don't worry, you got me!",
      "japanese": "みんな安心して戦って、あたしがついてるから！",
      "audioPath": "char_151_myrtle/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "Hmm?",
      "japanese": "ん～？",
      "audioPath": "char_151_myrtle/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "Whoa, almost dozed off...",
      "japanese": "うわっ、寝ちゃうところだった……。",
      "audioPath": "char_151_myrtle/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Good scenery here, Doctor!",
      "japanese": "ドクター、ここっていい景色だね！",
      "audioPath": "char_151_myrtle/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "I'm here to help!",
      "japanese": "みんな、助けに来たよ！",
      "audioPath": "char_151_myrtle/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "I have to get serious now!",
      "japanese": "本気で行くよ！",
      "audioPath": "char_151_myrtle/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "Gather around me, guys!",
      "japanese": "みんな、こっち来て！",
      "audioPath": "char_151_myrtle/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "We're counting on you again today, little apple.",
      "japanese": "リンゴちゃん、今日もよろしくね！",
      "audioPath": "char_151_myrtle/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "",
      "japanese": "",
      "audioPath": null
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "Phew, I'm exhausted! I wanna go to lie down, Doctor.",
      "japanese": "はぁ、はぁ……疲れた……ドクター、眠いからもう帰っていい？",
      "audioPath": "char_151_myrtle/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "Flawless victory! I was pretty good, wasn't I, Doctor?",
      "japanese": "だいしょーり！ドクター、あたしちゃんと役に立てた？",
      "audioPath": "char_151_myrtle/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "We won, Doctor, and that's what counts!",
      "japanese": "勝てたんだからそれでよし！ドクター、いちいち気にし過ぎると老けちゃうよってママが言ってたよ。",
      "audioPath": "char_151_myrtle/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "Run!",
      "japanese": "みんな、逃げるよ！",
      "audioPath": "char_151_myrtle/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "Wow, Rhodes Island is huge!",
      "japanese": "うわーロドスって広いね！",
      "audioPath": "char_151_myrtle/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Hey, that is fun!",
      "japanese": "面白いね！",
      "audioPath": "char_151_myrtle/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "Why can't the cafe open 24 hours?",
      "japanese": "どうして食堂は24時間やってないの？",
      "audioPath": "char_151_myrtle/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_151_myrtle/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Take the flag down, tie it up over here... Good! That's my cloth sack done! Oh, Doctor, you're here, too. Come, we'll eat up all the tasty food in the canteen! It's the first day of the year. Let's kick it off by eating our fill!",
      "japanese": "旗を取って、端っこを結んで、よし、袋の出来上がり！あ、ドクターもいたんだ。行くよ、食堂の美味しいものを全部すっからかんにしにしゅっぱーつ！新しい一年は、お腹いっぱい食べることから始めよう！",
      "audioPath": "char_151_myrtle/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Any more fun things to do, Doctor?",
      "japanese": "ドクター、なんか面白いことない？",
      "audioPath": "char_151_myrtle/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "I guess I followed Durin to a pretty nice place. I've seen huge nomadic cities, beaten up so many baddies in battle, and eaten so many great foods I'd never seen before. Once I get home, I'll turn all these stories into a travelogue and get it published. It's bound to be a bestseller!",
      "japanese": "ドゥリンを追って、結構いい所に来たんだよね。おっきな移動都市を見たし、戦場で悪い人もいっぱいやっつけたし、見たことのない美味しいものもたくさん食べた。里に帰って、この体験を旅行記にして本を出したら、絶対売れるよ！",
      "audioPath": "char_151_myrtle/CN_044.mp3"
    }
  ],
  "lappland": [
    {
      "fileCode": "CN_001",
      "label": "Appointed as Assistant",
      "category": "Talk",
      "english": "Ehi, Doctor. Hope you don't mind if I bring my weapons inside. I'll plop myself right over here.",
      "japanese": "やあ、ドクター。執務室に武器持ち込んでも許してくれるよね。ここ、座るよ。",
      "audioPath": "char_140_whitew/CN_001.mp3"
    },
    {
      "fileCode": "CN_002",
      "label": "Talk 1",
      "category": "Talk",
      "english": "Somebody out to get you, huh? Then have a long, hard think about who you might've wronged in the past.",
      "japanese": "誰かに狙われてる？じゃあしっかり思い出してみて、どこで恨みを買ったのかを。",
      "audioPath": "char_140_whitew/CN_002.mp3"
    },
    {
      "fileCode": "CN_003",
      "label": "Talk 2",
      "category": "Talk",
      "english": "If someone's out for revenge on you, don't hesitate, just take them out. Once you decide to pick up a weapon, you don't need a reason to kill.",
      "japanese": "もし復讐なんてしに来る奴がいたら、躊躇せず殺りなよ？一度武器を手にした相手は、殺すのに理由なんて要らないんだ。",
      "audioPath": "char_140_whitew/CN_003.mp3"
    },
    {
      "fileCode": "CN_004",
      "label": "Talk 3",
      "category": "Talk",
      "english": "It's been a while... I see that Texas made some friends. Hehehe... Affascinante! Can't wait to get to know them!",
      "japanese": "いつのまにかテキサスの周りもずいぶん賑やかになったね。ハハハ……いいね！ボクにもお友達を紹介してよ！",
      "audioPath": "char_140_whitew/CN_004.mp3"
    },
    {
      "fileCode": "CN_005",
      "label": "Talk after Promotion 1",
      "category": "Talk",
      "english": "You think I'm an assassin, huh? Yeah, alright. Call me whatever you want. I can be anyone, do anything, kill anyone anytime. Just so long as I want to!",
      "japanese": "ボクが殺し屋だって？いいよ、解釈は任せるよ！ボクは何者にだってなれるし、どんな仕事だってできる。そして、殺りたくなったらいつでも殺れる。ボクがそうしたいと思いさえすればね！",
      "audioPath": "char_140_whitew/CN_005.mp3"
    },
    {
      "fileCode": "CN_006",
      "label": "Talk after Promotion 2",
      "category": "Talk",
      "english": "I love power, Doctor. And you offered me a job where I can use my power to my heart's content... Love it. Honestly, the only joy I get out of this insane world is using my power to conquer it.",
      "japanese": "ボクは力が好きだよ、ドクター。そんなボクの力を存分に振るえる仕事をくれるキミはサイコーだ。この狂った世界で、まだ何か楽しみがあるとすれば、それはボクの力で全てをねじ伏せることぐらいさ！",
      "audioPath": "char_140_whitew/CN_006.mp3"
    },
    {
      "fileCode": "CN_007",
      "label": "Talk after Trust Increase 1",
      "category": "Talk",
      "english": "Texas? Ha, she's afraid of me, but I don't wanna do anything to her, except maybe try to bring back the old Texas. The one we got here's a cucciolo impaurito.",
      "japanese": "テキサス？フフッ、あの子はボクのことをものすごーく怖がってるけど、別に何かするつもりはないよ。ただ、ボクは昔のテキサスに戻ってもらいたいだけさ。今みたいな意気地なしじゃなかった頃のね……。",
      "audioPath": "char_140_whitew/CN_007.mp3"
    },
    {
      "fileCode": "CN_008",
      "label": "Talk after Trust Increase 2",
      "category": "Talk",
      "english": "That red one... oh... Doctor, keep her away from me! She'd definitely kill me in a fight. But I have this feeling... this feeling... ugh, why do I want to fight her so badly?",
      "japanese": "あれは……あの赤いの……まさか……！ドクター、絶対にアレに近づいちゃだめだ！でも、でも――チッ、不思議な感じだ、戦ったらきっと死んでしまうのに、こんなにもあの子と戦いたいなんて……！",
      "audioPath": "char_140_whitew/CN_008.mp3"
    },
    {
      "fileCode": "CN_009",
      "label": "Talk after Trust Increase 3",
      "category": "Talk",
      "english": "You want to know what happened between me and Texas? Hehe, you don't have a single idea of what you are sticking your nose into. You'll find out the truth someday, but not from me.",
      "japanese": "テキサスとの昔話が聞きたい？ハハ、怖いもの知らずだねキミは。まあ、いずれわかるさ。話すのはボクじゃないけどね。",
      "audioPath": "char_140_whitew/CN_009.mp3"
    },
    {
      "fileCode": "CN_010",
      "label": "Idle",
      "category": "Talk",
      "english": "Sleep tight... enjoy your sweet dreams while you still can.",
      "japanese": "眠るがいいさ……せめて今は甘い夢を。",
      "audioPath": "char_140_whitew/CN_010.mp3"
    },
    {
      "fileCode": "CN_011",
      "label": "Onboard",
      "category": "Talk",
      "english": "A great evil stands in the way of justice. My master, in the name of hatred and revenge, lead the weak onward!",
      "japanese": "正義の道は暴虐の使徒により断たれた。我が主よ、復讐と悪意の名の下に、弱き者を導き給え。",
      "audioPath": "char_140_whitew/CN_011.mp3"
    },
    {
      "fileCode": "CN_012",
      "label": "Watching Battle Record",
      "category": "Talk",
      "english": "Don't you just love how I keep getting more and more powerful?",
      "japanese": "どんどん強くなるボクの力、愛してくれるよね？",
      "audioPath": "char_140_whitew/CN_012.mp3"
    },
    {
      "fileCode": "CN_013",
      "label": "Promotion 1",
      "category": "Talk",
      "english": "Hahaha! Bene! I love how much you trust me. You can't say the same for Texas, right?",
      "japanese": "アハハ、キミの寵愛、確かに受け取ったよ。テキサスにはこれができるかな？",
      "audioPath": "char_140_whitew/CN_013.mp3"
    },
    {
      "fileCode": "CN_014",
      "label": "Promotion 2",
      "category": "Talk",
      "english": "Molto bene! That's more like it! Strength, unfettered and unchained! That's what I'm talking about!",
      "japanese": "そう、これでいい、もっともっと力を解き放とう！これはキミの使命だよ。",
      "audioPath": "char_140_whitew/CN_014.mp3"
    },
    {
      "fileCode": "CN_017",
      "label": "Added to Squad",
      "category": "Battle",
      "english": "Make Texas the leader!",
      "japanese": "隊長はテキサスにやってもらおう！",
      "audioPath": "char_140_whitew/CN_017.mp3"
    },
    {
      "fileCode": "CN_018",
      "label": "Appointed as Squad Leader",
      "category": "Battle",
      "english": "Put Texas on my team!",
      "japanese": "ボクのチームにはテキサスを入れてよ！",
      "audioPath": "char_140_whitew/CN_018.mp3"
    },
    {
      "fileCode": "CN_019",
      "label": "Depart",
      "category": "Battle",
      "english": "Haha, you people... I don't think I'll even remember your faces after this one... Anyway, let's just get started.",
      "japanese": "フッ……諸君、キミらの顔なんて覚えてられないけど……まあ、行こうか？",
      "audioPath": "char_140_whitew/CN_019.mp3"
    },
    {
      "fileCode": "CN_020",
      "label": "Begin Operation",
      "category": "Battle",
      "english": "We're fighting you guys? Then please do your bestest job, or I'll be really bored.",
      "japanese": "キミたちが敵？手加減なしで頼むよ？ボクに退屈させないで！",
      "audioPath": "char_140_whitew/CN_020.mp3"
    },
    {
      "fileCode": "CN_021",
      "label": "Selecting Operator 1",
      "category": "Battle",
      "english": "Show me what you've got.",
      "japanese": "お手並み拝見といこうか。",
      "audioPath": "char_140_whitew/CN_021.mp3"
    },
    {
      "fileCode": "CN_022",
      "label": "Selecting Operator 2",
      "category": "Battle",
      "english": "Tell me, what's your plan?",
      "japanese": "さて、どうするかな？",
      "audioPath": "char_140_whitew/CN_022.mp3"
    },
    {
      "fileCode": "CN_023",
      "label": "Deployment 1",
      "category": "Battle",
      "english": "Solid positioning.",
      "japanese": "悪くない位置取りだね！",
      "audioPath": "char_140_whitew/CN_023.mp3"
    },
    {
      "fileCode": "CN_024",
      "label": "Deployment 2",
      "category": "Battle",
      "english": "Ahahaha!",
      "japanese": "ハハッ！",
      "audioPath": "char_140_whitew/CN_024.mp3"
    },
    {
      "fileCode": "CN_025",
      "label": "In Battle 1",
      "category": "Battle",
      "english": "C'mon! C'eri quasi, tesoro!",
      "japanese": "ほら頑張れ？もうちょっとでボクに勝てるかもしれないよ！？",
      "audioPath": "char_140_whitew/CN_025.mp3"
    },
    {
      "fileCode": "CN_026",
      "label": "In Battle 2",
      "category": "Battle",
      "english": "Can you do it?",
      "japanese": "キミにできるかな？",
      "audioPath": "char_140_whitew/CN_026.mp3"
    },
    {
      "fileCode": "CN_027",
      "label": "In Battle 3",
      "category": "Battle",
      "english": "Just try me!",
      "japanese": "抗ってみなよ！",
      "audioPath": "char_140_whitew/CN_027.mp3"
    },
    {
      "fileCode": "CN_028",
      "label": "In Battle 4",
      "category": "Battle",
      "english": "You'll have to try harder than that!",
      "japanese": "さぁ、あと少し！",
      "audioPath": "char_140_whitew/CN_028.mp3"
    },
    {
      "fileCode": "CN_029",
      "label": "4-star Result",
      "category": "Battle",
      "english": "It's over? Ah, che noia!",
      "japanese": "この程度で終わりなの？つまらないなあ。",
      "audioPath": "char_140_whitew/CN_029.mp3"
    },
    {
      "fileCode": "CN_030",
      "label": "3-star Result",
      "category": "Battle",
      "english": "Hahaha, sliced 'em up like a millefoglie. How do you like it?",
      "japanese": "フフ、ボクお手製のミルフィーユ、味はどうだい？",
      "audioPath": "char_140_whitew/CN_030.mp3"
    },
    {
      "fileCode": "CN_031",
      "label": "Sub 3-star Result",
      "category": "Battle",
      "english": "Not my best work. You can lay it on me for letting a few get away.",
      "japanese": "まあまあかな。何人か逃したのはボクの責任だね。",
      "audioPath": "char_140_whitew/CN_031.mp3"
    },
    {
      "fileCode": "CN_032",
      "label": "Operation Failure",
      "category": "Battle",
      "english": "Bravo! Now I want to crush them that much harder! Hahaha!",
      "japanese": "サイッコーだね、アイツらをぶっ殺してやりたい欲望が、ますます高ぶってきたよ！アハハ！",
      "audioPath": "char_140_whitew/CN_032.mp3"
    },
    {
      "fileCode": "CN_033",
      "label": "Assigned to Facility",
      "category": "Talk",
      "english": "Hm? Did I see a red shadow flash by?",
      "japanese": "あれ……赤い影が一瞬見えた気がする。",
      "audioPath": "char_140_whitew/CN_033.mp3"
    },
    {
      "fileCode": "CN_034",
      "label": "Tap",
      "category": "Talk",
      "english": "Haha!",
      "japanese": "ハハッ。",
      "audioPath": "char_140_whitew/CN_034.mp3"
    },
    {
      "fileCode": "CN_036",
      "label": "Trust Tap",
      "category": "Talk",
      "english": "The more I get to know you, the better I understand Texas. I Love it.",
      "japanese": "キミのことを知れば知るほど、テキサスのこともわかってくる。サイコーだね。",
      "audioPath": "char_140_whitew/CN_036.mp3"
    },
    {
      "fileCode": "CN_037",
      "label": "Title",
      "category": "Talk",
      "english": "Arknights.",
      "japanese": "アークナイツ。",
      "audioPath": "char_140_whitew/CN_037.mp3"
    },
    {
      "fileCode": "CN_038",
      "label": "New Year's blessing",
      "category": "Talk",
      "english": "Where's Texas? It's almost time for the countdown, shouldn't she be at Rhodes Island? Hah, to think I don't even get to see her on a day like this. Where are those precious friends of hers? I'm going to find Texas. Wanna come with, Doctor?",
      "japanese": "テキサスはどこかな？そろそろカウントダウンだし、まさかロドスにいないわけないよね？ハハッ、せっかくの記念すべき日なのに全然姿を見せないし、いつものお友達までどこに消えちゃったの？ちょっと探してみようと思うんだけど、ドクターも来る？",
      "audioPath": "char_140_whitew/CN_038.mp3"
    },
    {
      "fileCode": "CN_042",
      "label": "Greeting",
      "category": "Greeting",
      "english": "Heh. Ciao, Doctor.",
      "japanese": "フフッ、おはよう、ドクター。",
      "audioPath": "char_140_whitew/CN_042.mp3"
    },
    {
      "fileCode": "CN_044",
      "label": "Anniversary Celebration",
      "category": "Talk",
      "english": "Here, take some whiskey, add a little amaretto, then put it on the rocks. Wanna sip? Hehe. In Siracusa, we call this a 'Luci Spente,' and one sip means you're killing the guy next to you. Texas? She'll never tell you this, but she used to love this drink. Come, salute!",
      "japanese": "はい、ウイスキーだよ、アマレットを垂らしてロックで召し上がれ。まさか一気飲みするつもり？フフッ……シラクーザではね、このカクテルは「ルーチェ・スペンテ」って呼ばれてるんだけど、一口で飲み干したら隣の奴を殺すって意味になるんだ。テキサスからは聞いてない？あの子は君にこんな話なんてしないでしょ。でもこの味はあの子のお気に入りだったんだ。さあ、乾杯しよ。",
      "audioPath": "char_140_whitew/CN_044.mp3"
    }
  ]
}
